/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "gtfs_realtime.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(transit_realtime_FeedHeader, transit_realtime_FeedHeader, AUTO)


PB_BIND(transit_realtime_TripDescriptor, transit_realtime_TripDescriptor, AUTO)


PB_BIND(transit_realtime_TripUpdate, transit_realtime_TripUpdate, AUTO)


PB_BIND(transit_realtime_TripUpdate_StopTimeEvent, transit_realtime_TripUpdate_StopTimeEvent, AUTO)


PB_BIND(transit_realtime_TripUpdate_StopTimeUpdate, transit_realtime_TripUpdate_StopTimeUpdate, AUTO)


PB_BIND(transit_realtime_Position, transit_realtime_Position, AUTO)


PB_BIND(transit_realtime_VehiclePosition, transit_realtime_VehiclePosition, AUTO)


PB_BIND(transit_realtime_FeedEntity, transit_realtime_FeedEntity, AUTO)


PB_BIND(transit_realtime_FeedMessage, transit_realtime_FeedMessage, 4)









